#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="${QUANT_WORKSPACE_DIR:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

PROD_ROOT="${QUANT_PROD_ROOT:-${HOME}/Library/Application Support/quant_service_prod}"
PROD_APP_DIR="${QUANT_PROD_APP_DIR:-${PROD_ROOT}/current}"
PROD_RELEASES_DIR="${QUANT_PROD_RELEASES_DIR:-${PROD_ROOT}/releases}"
PROD_VENV_DIR="${QUANT_PROD_VENV_DIR:-${PROD_ROOT}/venv}"
PROD_DATA_DIR="${QUANT_PROD_DATA_DIR:-${PROD_ROOT}/data}"
PROD_LOG_DIR="${QUANT_PROD_LOG_DIR:-${PROD_ROOT}/logs}"
PROD_TMP_DIR="${QUANT_PROD_TMP_DIR:-${PROD_ROOT}/tmp}"
PROD_DEPLOY_LOCK_DIR="${QUANT_PROD_DEPLOY_LOCK_DIR:-${PROD_ROOT}/deploy.lock}"
PROD_ENV_FILE="${QUANT_PROD_ENV_FILE:-${PROD_ROOT}/prod.env}"

PROD_PYTHON="${QUANT_PROD_PYTHON:-}"
if [ -z "${PROD_PYTHON}" ]; then
    if command -v python3.12 >/dev/null 2>&1; then
        PROD_PYTHON="$(command -v python3.12)"
    elif command -v python3.11 >/dev/null 2>&1; then
        PROD_PYTHON="$(command -v python3.11)"
    elif [ -x "${WORKSPACE_DIR}/.venv/bin/python" ]; then
        PROD_PYTHON="${WORKSPACE_DIR}/.venv/bin/python"
    else
        PROD_PYTHON="$(command -v python3)"
    fi
fi

PROD_SERVICE_LABEL="${QUANT_PROD_SERVICE_LABEL:-com.jiangjiuwen.quant-service}"
PROD_BACKFILL_LABEL="${QUANT_PROD_BACKFILL_LABEL:-com.jiangjiuwen.quant-service.backfill}"
PROD_WATCH_LABEL="${QUANT_PROD_WATCH_LABEL:-com.jiangjiuwen.quant-service.watch}"

LAUNCH_AGENTS_DIR="${HOME}/Library/LaunchAgents"
PROD_SERVICE_PLIST="${LAUNCH_AGENTS_DIR}/${PROD_SERVICE_LABEL}.plist"
PROD_BACKFILL_PLIST="${LAUNCH_AGENTS_DIR}/${PROD_BACKFILL_LABEL}.plist"
PROD_WATCH_PLIST="${LAUNCH_AGENTS_DIR}/${PROD_WATCH_LABEL}.plist"

PROD_API_PORT="${QUANT_PROD_API_PORT:-18000}"
PROD_API_HOST="${QUANT_PROD_API_HOST:-127.0.0.1}"
PROD_BATCH_SIZE="${QUANT_PROD_BATCH_SIZE:-100}"
PROD_HISTORY_YEARS="${QUANT_PROD_HISTORY_YEARS:-15}"
PROD_START_YEAR="${QUANT_PROD_START_YEAR:-2010}"
PROD_LOG_LEVEL="${QUANT_PROD_LOG_LEVEL:-INFO}"
PROD_SYNC_HOUR="${QUANT_PROD_SYNC_HOUR:-15}"
PROD_SYNC_MINUTE="${QUANT_PROD_SYNC_MINUTE:-30}"

KEEP_RELEASES="${QUANT_PROD_KEEP_RELEASES:-5}"
WATCH_POLL_SECONDS="${QUANT_PROD_WATCH_POLL_SECONDS:-2}"
WATCH_DEBOUNCE_SECONDS="${QUANT_PROD_WATCH_DEBOUNCE_SECONDS:-3}"

SERVICE_STDOUT_LOG="${PROD_LOG_DIR}/service.stdout.log"
SERVICE_STDERR_LOG="${PROD_LOG_DIR}/service.stderr.log"
BACKFILL_STDOUT_LOG="${PROD_LOG_DIR}/backfill.stdout.log"
BACKFILL_STDERR_LOG="${PROD_LOG_DIR}/backfill.stderr.log"
WATCH_STDOUT_LOG="${PROD_LOG_DIR}/watch.stdout.log"
WATCH_STDERR_LOG="${PROD_LOG_DIR}/watch.stderr.log"
BACKFILL_STATE_FILE="${PROD_DATA_DIR}/backfill_state.json"
WATCH_STATE_FILE="${PROD_ROOT}/watch_state.json"

GUI_DOMAIN="gui/$(id -u)"

export WORKSPACE_DIR PROD_ROOT PROD_APP_DIR PROD_RELEASES_DIR PROD_VENV_DIR PROD_DATA_DIR PROD_LOG_DIR
export PROD_TMP_DIR PROD_DEPLOY_LOCK_DIR PROD_ENV_FILE
export PROD_PYTHON
export PROD_SERVICE_LABEL PROD_BACKFILL_LABEL PROD_WATCH_LABEL
export LAUNCH_AGENTS_DIR PROD_SERVICE_PLIST PROD_BACKFILL_PLIST PROD_WATCH_PLIST
export PROD_API_PORT PROD_API_HOST PROD_BATCH_SIZE PROD_HISTORY_YEARS PROD_START_YEAR PROD_LOG_LEVEL
export PROD_SYNC_HOUR PROD_SYNC_MINUTE
export KEEP_RELEASES WATCH_POLL_SECONDS WATCH_DEBOUNCE_SECONDS
export SERVICE_STDOUT_LOG SERVICE_STDERR_LOG BACKFILL_STDOUT_LOG BACKFILL_STDERR_LOG
export WATCH_STDOUT_LOG WATCH_STDERR_LOG BACKFILL_STATE_FILE WATCH_STATE_FILE GUI_DOMAIN
